# Simple queries

# Works by Stefan Zweig on Inventaire
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?work WHERE {
  ?work wdt:P50 wd:Q78491 .
}

###

# Works by Stefan Zweig on Inventaire, their editions, and the ISBN of those editions
# NB: this doesn't include Stefan Zweig already on Wikidata, and neither their editions
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?work ?edition ?isbn WHERE {
  ?work wdt:P50 wd:Q78491 .
  ?edition wdt:P629 ?work .
  OPTIONAL { ?edition wdt:P212 ?isbn . }
}

###

# Number of editions per year
#defaultView:LineChart
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>

SELECT ?year (COUNT(?edition) AS ?count) WHERE {
  ?edition wdt:P31 wd:Q3331189 ;
           wdt:P577 ?publication_date .
  BIND(str(YEAR(?publication_date)) AS ?year)
}
GROUP BY ?year
