# Maintainance

# Authors without work
SELECT ?author WHERE {
  ?author wdt:P31 wd:Q5 .
  # '?property' may be: wdt:P50, wdt:P2679, or wdt:P2680
  FILTER NOT EXISTS { ?work ?property ?author . }
}

###

# Editions without work
SELECT ?edition WHERE {
  ?edition wdt:P31 wd:Q3331189 .
  FILTER NOT EXISTS { ?edition wdt:P629 ?work . }
}

###

# Editions without publisher
SELECT ?edition WHERE {
  ?edition wdt:P31 wd:Q3331189 .
  FILTER NOT EXISTS { ?edition wdt:P123 ?publisher . }
}

###

# Editions without language
SELECT ?edition WHERE {
  ?edition wdt:P31 wd:Q3331189 .
  FILTER NOT EXISTS { ?edition wdt:P407 ?language . }
}

###

# Editions without cover
SELECT ?edition WHERE {
  ?edition wdt:P31 wd:Q3331189 .
  FILTER NOT EXISTS { ?edition invp:P2 ?cover . }
}

###

# Editions without ISBN
SELECT ?edition WHERE {
  ?edition wdt:P31 wd:Q3331189 .
  FILTER NOT EXISTS { ?edition wdt:P212 ?isbn . }
}

###

# Work without edition
SELECT ?work WHERE {
  ?work wdt:P31 wd:Q571 .
  FILTER NOT EXISTS { ?edition wdt:P629 ?work . }
}

###

# Work without author
SELECT ?work WHERE {
  ?work wdt:P31 wd:Q571 .
  FILTER NOT EXISTS { ?work wdt:P50 ?author . }
}

###

# Author without work
SELECT ?author WHERE {
  ?author wdt:P31 wd:Q5 .
  FILTER NOT EXISTS { ?work wdt:P50 ?author . }
}

###

# type of Wikidata entities used by Inventaire items
SELECT ?type ?typeLabel (COUNT(?item) AS ?count ) WHERE {
  hint:Query hint:optimizer "None".
  ?item wdt:P1574 ?entity .
  FILTER(STRSTARTS(STR(?entity), 'http://www.wikidata.org/entity/Q')) .
  SERVICE wdq:sparql {
    ?entity wdt:P31 ?type .
    ?type rdfs:label ?typeLabel .
    FILTER(LANG(?typeLabel) = "en") .
  }
}
GROUP BY ?type ?typeLabel

###

# Authors with non-alphabetical chars
# Except whitespace - . ' and latin chars (éùàç...)
SELECT ?author ?label WHERE {
  ?author wdt:P31 wd:Q5 .
  ?author rdfs:label ?label .
  FILTER(REGEX(STR(?label), "[^a-zA-Z\\d\\s:\u00C0-\u024F'.-]", 'i')) .
}

###

# Authors that aren't used in any claim and where never edited
# Recommanded admin action: delete
SELECT ?author WHERE {
  ?author wdt:P31 wd:Q5 ;
          schema:version "2"^^xsd:integer ;
          wikibase:labels "1"^^xsd:integer ;
          wikibase:statements "1"^^xsd:integer ;
  FILTER NOT EXISTS { ?work ?property ?author . }
